const DEFAULT_CRITERIA = [
  'Std. 0 < 0.250',
  'Std. 1 / Std. 0 > 1.9',
  'Std. 4 > 1',
  'Std. 4 / Std. 1 > 3',
]

export const ALLERGENS = [
  {
    id: 'histamine',
    name: 'Histamine ELISA',
    unit: 'ppm',
    assayFormat: 'competitive',
    standards: [
      { std: '0', concentration: 0,  meanOD: 1.984, cv: 2.2 },
      { std: '1', concentration: 2,  meanOD: 1.526, cv: 3.1 },
      { std: '2', concentration: 6,  meanOD: 1.007, cv: 5.4 },
      { std: '3', concentration: 12, meanOD: 0.761, cv: 7.0 },
      { std: '4', concentration: 24, meanOD: 0.521, cv: 3.9 },
      { std: '5', concentration: 72, meanOD: 0.390, cv: 3.6 },
    ],
    criteria: [
      'Blank OD adequate (> 0.5)',
      'Signal inhibition at Std. N (Std. 0 / Std. N > 2.0×)',
      'OD values decrease with increasing concentration',
      'Curve fit R² ≥ 0.99',
    ],
  },
  {
    id: 'almond',
    name: 'Almond ELISA',
    unit: 'ppm',
    assayFormat: 'sandwich',
    standards: [
      { std: '0', concentration: 0    },
      { std: '1', concentration: 0.5  },
      { std: '2', concentration: 2    },
      { std: '3', concentration: 5    },
      { std: '4', concentration: 10   },
    ],
    criteria: DEFAULT_CRITERIA,
  },
  {
    id: 'blg',
    name: 'BLG ELISA',
    unit: 'ppb',
    assayFormat: 'sandwich',
    standards: [
      { std: '0', concentration: 0   },
      { std: '1', concentration: 10  },
      { std: '2', concentration: 50  },
      { std: '3', concentration: 150 },
      { std: '4', concentration: 300 },
    ],
    criteria: ['Std. 0 < 0.250', 'Std. 1 / Std. 0 > 1.25', 'Std. 4 > 1', 'Std. 4 / Std. 1 > 3'],
  },
  {
    id: 'casein',
    name: 'Casein ELISA',
    unit: 'ppm',
    assayFormat: 'sandwich',
    standards: [
      { std: '0', concentration: 0   },
      { std: '1', concentration: 0.2 },
      { std: '2', concentration: 1   },
      { std: '3', concentration: 2.5 },
      { std: '4', concentration: 5   },
    ],
    criteria: DEFAULT_CRITERIA,
  },
  {
    id: 'cashew',
    name: 'Cashew ELISA',
    unit: 'ppm',
    assayFormat: 'sandwich',
    standards: [
      { std: '0', concentration: 0  },
      { std: '1', concentration: 2  },
      { std: '2', concentration: 10 },
      { std: '3', concentration: 25 },
      { std: '4', concentration: 50 },
    ],
    criteria: DEFAULT_CRITERIA,
  },
  {
    id: 'coconut',
    name: 'Coconut ELISA',
    unit: 'ppm',
    assayFormat: 'sandwich',
    standards: [
      { std: '0', concentration: 0    },
      { std: '1', concentration: 2    },
      { std: '2', concentration: 5    },
      { std: '3', concentration: 12.5 },
      { std: '4', concentration: 25   },
    ],
    criteria: DEFAULT_CRITERIA,
  },
  {
    id: 'crustacean',
    name: 'Crustacean ELISA',
    unit: 'ppb',
    assayFormat: 'sandwich',
    standards: [
      { std: '0', concentration: 0   },
      { std: '1', concentration: 20  },
      { std: '2', concentration: 80  },
      { std: '3', concentration: 200 },
      { std: '4', concentration: 400 },
    ],
    criteria: DEFAULT_CRITERIA,
  },
  {
    id: 'egg',
    name: 'Egg ELISA',
    unit: 'ppm',
    assayFormat: 'sandwich',
    standards: [
      { std: '0', concentration: 0   },
      { std: '1', concentration: 0.4 },
      { std: '2', concentration: 2   },
      { std: '3', concentration: 4   },
      { std: '4', concentration: 8   },
    ],
    criteria: DEFAULT_CRITERIA,
  },
  {
    id: 'fish',
    name: 'Fish ELISA',
    unit: 'ppm',
    assayFormat: 'sandwich',
    standards: [
      { std: '0', concentration: 0   },
      { std: '1', concentration: 4   },
      { std: '2', concentration: 20  },
      { std: '3', concentration: 50  },
      { std: '4', concentration: 100 },
    ],
    criteria: DEFAULT_CRITERIA,
  },
  {
    id: 'hazelnut',
    name: 'Hazelnut ELISA',
    unit: 'ppm',
    assayFormat: 'sandwich',
    standards: [
      { std: '0', concentration: 0  },
      { std: '1', concentration: 1  },
      { std: '2', concentration: 5  },
      { std: '3', concentration: 15 },
      { std: '4', concentration: 40 },
    ],
    criteria: DEFAULT_CRITERIA,
  },
  {
    id: 'lupine',
    name: 'Lupine ELISA',
    unit: 'ppm',
    assayFormat: 'sandwich',
    standards: [
      { std: '0', concentration: 0  },
      { std: '1', concentration: 2  },
      { std: '2', concentration: 5  },
      { std: '3', concentration: 15 },
      { std: '4', concentration: 30 },
    ],
    criteria: DEFAULT_CRITERIA,
  },
  {
    id: 'lysozyme',
    name: 'Lysozyme ELISA',
    unit: 'ppb',
    assayFormat: 'sandwich',
    standards: [
      { std: '0', concentration: 0   },
      { std: '1', concentration: 25  },
      { std: '2', concentration: 50  },
      { std: '3', concentration: 125 },
      { std: '4', concentration: 250 },
    ],
    criteria: DEFAULT_CRITERIA,
  },
  {
    id: 'macadamia',
    name: 'Macadamia ELISA',
    unit: 'ppm',
    assayFormat: 'sandwich',
    standards: [
      { std: '0', concentration: 0    },
      { std: '1', concentration: 1    },
      { std: '2', concentration: 5    },
      { std: '3', concentration: 12.5 },
      { std: '4', concentration: 25   },
    ],
    criteria: DEFAULT_CRITERIA,
  },
  {
    id: 'milk',
    name: 'Milk ELISA',
    unit: 'ppm',
    assayFormat: 'sandwich',
    standards: [
      { std: '0', concentration: 0   },
      { std: '1', concentration: 0.5 },
      { std: '2', concentration: 2   },
      { std: '3', concentration: 5   },
      { std: '4', concentration: 10  },
    ],
    criteria: DEFAULT_CRITERIA,
  },
  {
    id: 'mustard',
    name: 'Mustard ELISA',
    unit: 'ppm',
    assayFormat: 'sandwich',
    standards: [
      { std: '0', concentration: 0  },
      { std: '1', concentration: 2  },
      { std: '2', concentration: 10 },
      { std: '3', concentration: 25 },
      { std: '4', concentration: 50 },
    ],
    criteria: DEFAULT_CRITERIA,
  },
  {
    id: 'ova',
    name: 'OVA ELISA',
    unit: 'ppb',
    assayFormat: 'sandwich',
    standards: [
      { std: '0', concentration: 0   },
      { std: '1', concentration: 25  },
      { std: '2', concentration: 100 },
      { std: '3', concentration: 250 },
      { std: '4', concentration: 500 },
    ],
    criteria: DEFAULT_CRITERIA,
  },
  {
    id: 'peanut',
    name: 'Peanut ELISA',
    unit: 'ppm',
    assayFormat: 'sandwich',
    standards: [
      { std: '0', concentration: 0  },
      { std: '1', concentration: 1  },
      { std: '2', concentration: 5  },
      { std: '3', concentration: 15 },
      { std: '4', concentration: 30 },
    ],
    criteria: DEFAULT_CRITERIA,
  },
  {
    id: 'pistachio',
    name: 'Pistachio ELISA',
    unit: 'ppm',
    assayFormat: 'sandwich',
    standards: [
      { std: '0', concentration: 0    },
      { std: '1', concentration: 1    },
      { std: '2', concentration: 5    },
      { std: '3', concentration: 12.5 },
      { std: '4', concentration: 25   },
    ],
    criteria: DEFAULT_CRITERIA,
  },
  {
    id: 'sesame',
    name: 'Sesame ELISA',
    unit: 'ppm',
    assayFormat: 'sandwich',
    standards: [
      { std: '0', concentration: 0  },
      { std: '1', concentration: 2  },
      { std: '2', concentration: 4  },
      { std: '3', concentration: 10 },
      { std: '4', concentration: 20 },
    ],
    criteria: DEFAULT_CRITERIA,
  },
  {
    id: 'soy',
    name: 'Soy (STI) ELISA',
    unit: 'ppb',
    assayFormat: 'sandwich',
    standards: [
      { std: '0', concentration: 0   },
      { std: '1', concentration: 50  },
      { std: '2', concentration: 150 },
      { std: '3', concentration: 300 },
      { std: '4', concentration: 600 },
    ],
    criteria: DEFAULT_CRITERIA,
  },
  {
    id: 'walnut',
    name: 'Walnut ELISA',
    unit: 'ppm',
    assayFormat: 'sandwich',
    standards: [
      { std: '0', concentration: 0  },
      { std: '1', concentration: 2  },
      { std: '2', concentration: 5  },
      { std: '3', concentration: 15 },
      { std: '4', concentration: 50 },
    ],
    criteria: DEFAULT_CRITERIA,
  },
]

export function getAllergen(id) {
  return ALLERGENS.find(a => a.id === id) || ALLERGENS[0]
}
